version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/Bibob7/go-eventstore

issues:
  max-same-issues: 0
